# Generated by Django 2.2.8 on 2019-12-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_auto_20191218_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
