# Generated by Django 2.0.2 on 2020-01-24 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0011_auto_20200117_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 10, 55, 577015, tzinfo=utc)),
        ),
    ]
