# Generated by Django 2.0.2 on 2020-01-24 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0012_auto_20200124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 17, 1, 26, 4396, tzinfo=utc)),
        ),
    ]
