# Generated by Django 2.0.2 on 2020-01-23 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0012_auto_20200122_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 14, 9, 36, 945543, tzinfo=utc)),
        ),
    ]
