# Generated by Django 2.0.2 on 2020-01-26 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0014_auto_20200125_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 10, 11, 39, 147503, tzinfo=utc)),
        ),
    ]
