# Generated by Django 2.0.2 on 2020-01-29 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0015_auto_20200126_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 11, 9, 56, 131190, tzinfo=utc)),
        ),
    ]
