# Generated by Django 2.0.2 on 2021-01-29 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0016_auto_20210125_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 20, 8, 31, 868623, tzinfo=utc)),
        ),
    ]
