# Generated by Django 2.0.2 on 2021-01-29 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0017_auto_20210130_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 21, 26, 11, 838287, tzinfo=utc)),
        ),
    ]
