# Generated by Django 2.0.2 on 2021-01-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0017_auto_20210126_1301'),
        ('photoapp', '0019_auto_20210130_0257'),
    ]

    operations = [
    ]
