# Generated by Django 2.0.2 on 2021-01-30 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0020_merge_20210130_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nolike',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 18, 14, 58, 51365, tzinfo=utc)),
        ),
    ]
