# Generated by Django 2.0.2 on 2020-01-30 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0020_auto_20200130_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 19, 2, 52, 111386, tzinfo=utc)),
        ),
    ]
