# Generated by Django 2.2.8 on 2019-12-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='location',
        ),
    ]
